name: action test
on: 
  push: 
    branches:
      - master
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - name: login heroku 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:login

      - name: Build the Docker image
        run: docker build -t web:latest .

      - name: Push the Docker image to the Heroku registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: |
          heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
          heroku ps:scale web=1 -a ${{ secrets.HEROKU_APP_NAME }}
        
  check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r ./django-test/requirements-dev.txt

      - name: Migrate db
        run: python ./django-test/manage.py migrate

      - name: Test with pytest
        run: pytest